apiVersion: apps/v1
kind: Deployment
metadata:
  name: ct-web
  namespace: ct-app-ns
  labels:
    app: ct-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-web
  template:
    metadata:
      labels:
        app: ct-web
    spec:
      containers:
      - name: ct-web
        image: saichandrasekar/ct-web:1.0.3
        ports:
        - containerPort: 18080
