apiVersion: v1
kind: Service
metadata:
  name: ct-web-service
  namespace: ct-app-ns
spec:
  selector:
    app: ct-web
  type: NodePort
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 18080
